num1 = int(input("Enter the first integer: "))
num2 = int(input("Enter the second integer: "))
num3 = int(input("Enter the third integer: "))
print("The sum of the three integers is:", num1 + num2 + num3)
print("The first number minus the second number is:", num1 - num2)
print("The third number multiplied by the first number is:", num3 * num1)
print("The sum of all three numbers divided by the third number is:", (num1 + num2 + num3) / num3)